# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-09 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.BaseModel')),
                ('descripcion', models.TextField(null=True)),
                ('encabazado', models.CharField(max_length=5000)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('foto', models.ImageField(null=True, upload_to=b'')),
            ],
            bases=('stores.basemodel',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stores.BaseModel')),
                ('nombre', models.CharField(max_length=500)),
                ('logo', models.ImageField(null=True, upload_to=b'')),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('facebook', models.URLField(null=True)),
                ('twitter', models.URLField(null=True)),
                ('direccion', models.CharField(max_length=500)),
                ('latitud', models.DecimalField(decimal_places=16, max_digits=20)),
                ('longitud', models.DecimalField(decimal_places=16, max_digits=20)),
            ],
            bases=('stores.basemodel',),
        ),
    ]
