# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='promocion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stores.Store'),
            preserve_default=False,
        ),
    ]
