# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-14 04:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20190814_0450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='from_store',
            new_name='tienda',
        ),
    ]
